apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-deplyment
    namespace: default
spec:
    replicas: 2
    selector:
        matchLabels:
            app: myapp
            release: stable
    template:
        metadata:
            labels:
                app: myapp
                release: stable
                isPublish: "Yes"
        spec:
            containers:
            - name: myapp
              image: recminy/nginx:1.18
              ports:
              - name: myweb
                containerPort: 80
